name: Test and Publish Allure Reports to GHPages
run-name: Test and Publish Allure Reports to GHPages

on:
  workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from GitHub Actions"
