name: Static HTML - Test then publish Reports to GH Pages
run-name: Static HTML - Test then publish Reports to GH Pages

on:
  # This job can only be triggered manually
  workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job Name
  run-e2e-test:
    
    # Runner will run with this OS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          # Cache dependencies from pom.xml, reduces run time by only downloading new dependencies
          cache: 'maven'
      - name: Run EndToEnd Test
        run: mvn test
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Path to artifacts
          path: target/surefire-reports

  deploy-test-results:
    runs-on: ubuntu-latest
    needs: run-e2e-test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Display GH Pages URL / Reports Page
        run: echo "https://carlnoval.github.io/gh-actions"
